### ISSUE TITLE
argparse does not support the '--' end option indicator

### ISSUE THREAD

**Issue by dgsb** [kierdavis/argparse#3]
The accepted way to handle command line parameter which starts with a '-' but is not a command line option is to indicate the end of option by a '--' then all following parameter are interpreted as positional parameter whatever they start with a '-' or not.

**Comment by kierdavis** [comment]
https://github.com/kierdavis/argparse/commit/dd4252a202da02b4b6df938a61341d0599c990dd should implement this behaviour
